/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  assigner: string;
  owner?: string | null;
}
export type ExecuteMsg = {
  assign: {
    address: string;
    checkmark_id: string;
  };
} | {
  delete: {};
} | {
  revoke_checkmark: {
    checkmark_id: string;
  };
} | {
  revoke_address: {
    address: string;
  };
} | {
  update_checkmark_ban: {
    ban_ids?: string[] | null;
    unban_ids?: string[] | null;
  };
} | {
  update_assigner: {
    assigner: string;
  };
} | {
  update_ownership: Action;
};
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type QueryMsg = {
  get_checkmark: {
    address: string;
  };
} | {
  get_address: {
    checkmark_id: string;
  };
} | {
  count: {};
} | {
  checkmark_banned: {
    checkmark_id: string;
  };
} | {
  assigner: {};
} | {
  ownership: {};
};
export type Addr = string;
export interface AssignerResponse {
  assigner: Addr;
}
export interface CheckmarkBannedResponse {
  banned: boolean;
}
export interface CountResponse {
  count: number;
}
export interface GetAddressResponse {
  address?: Addr | null;
}
export interface GetCheckmarkResponse {
  checkmark_id?: string | null;
}
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}